language: python
python:
  - "3.5"

services: postgresql

env:
  - DJANGO_SETTINGS_MODULE=djcon_chart.test_settings
  - SAUCE_USERNAME=RedBeardCode
  - SAUCE_ACCESS_KEY=7a21a467-c36b-4469-9a5b-46dec9959dbb
  - SAUCE_BROWSER=chrome

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install flaky
  - pip install pytest-timeout
  - pip install psycopg2

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres;

script:
  - python manage.py makemigrations control_chart
  - python manage.py migrate
  - python manage.py createtestdata
  - py.test --timeout=60 --force-flaky --max-run=5 --phantomjs 

addons:
  sauce_connect: true

