language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

services: postgresql

env:
  - DJANGO=1.9
  - DJANGO_SETTINGS_MODULE=djcon_chart.test_settings


install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install psycopg2

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py createtestdata
  - py.test