language: python
python:
  - "3.5"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=djcon_chart.test_settings
    - SAUCE_BROWSER=chrome

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install flaky
  - pip install pytest-timeout
  - pip install psycopg2

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres;

script:
  - python manage.py makemigrations control_chart
  - python manage.py migrate
  - python manage.py createtestdata
  - py.test -s --timeout=60 --force-flaky --max-run=5 --ci

addons:
  sauce_connect: true

