language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=djcon_chart.test_settings
  matrix:
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10"
    - SAUCE_BROWSER="firefox" SAUCE_PLATFORM="Windows 10"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="linux"
    - SAUCE_BROWSER="firefox" SAUCE_PLATFORM="linux"


install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install flaky
  - pip install pytest-timeout
  - pip install psycopg2

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres;

script:
  - python manage.py makemigrations control_chart
  - python manage.py migrate
  - python manage.py createtestdata
  - py.test --timeout=60 --force-flaky --max-run=5 --ci --cov-config .coveragerc --cov=control_chart --cov=djcon_chart

addons:
  sauce_connect: true

after_success:
  - coveralls

