language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py createtestdata
  - py.test