language: python
python:
  - "2.7"
  - "3.5"

services: postgresql

cache: pip

env:
  global:
    - DJANGO_SETTINGS_MODULE=djcon_chart.test_settings
  matrix:
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="admin"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="base_layout"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="calculation_rule"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="characteristic_value"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="paginator"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="measurement"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="item_and_order"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="plot"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="product"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="recalculation"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10" TEST_PATTERN="user_groups"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="admin"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="base_layout"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="calculation_rule"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="characteristic_value"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="paginator"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="measurement"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="item_and_order"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="plot"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="product"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="recalculation"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux" TEST_PATTERN="user_groups"



install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install flaky
  - pip install pytest-timeout
  - pip install psycopg2

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres;

script:
  - python manage.py makemigrations control_chart
  - python manage.py migrate
  - python manage.py createtestdata
  - py.test --timeout=30 --force-flaky --max-run=2 --ci --cov-config .coveragerc --cov=control_chart --cov=djcon_chart -k $TEST_PATTERN

addons:
  sauce_connect: true

after_success:
  - coveralls

