web:
  restart: always
  build: ./
  expose:
    - "8000"
    - "5006"
    - "80"
  links:
    - postgres:postgres
    - bokeh:bokeh
  volumes:
    - ./:/app
  env_file: .env

nginx:
  restart: always
  build: ./dockers/nginx/
  ports:
    - "81:80"
  volumes:
    - /www/static
  volumes_from:
    - web
    - bokeh
  links:
    - web:web
    - bokeh:bokeh

bokeh:
  restart: always
  build: ./dockers/bokeh/
  expose:
    - "5006"
    - "80"
  volumes:
      - /usr/local/lib/python3.5/site-packages/bokeh/server/static/


postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5433:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/
